#!/bin/bash
filename=$1
a=OUTCAR  # in vasp, the format of output data is fixed in OUTCAR
echo $filename
echo $a
if  [ "$filename" == "$a" ]; then
echo "generated by VASP" &
grep "TOTEN" $filename
elif [ 1 == 1 ] ; then
 if grep "total en" $filename ; then  echo "generated by QE"   # format in QE
 else 
 grep "dE" $filename ; echo "generated by QW"   #format in QW
 fi
fi



#Author: Yue-Wen Fang
#Contact: fyuewen@gmail.com
#Creation time: Sept. 11th, 2015




#below is just for VASP and QE
#filename=$1
#a=OUTCAR
#echo $filename
#echo $a
#if  [ "$filename" == "$a" ]; then
#echo "generated by VASP" &
#grep "TOTEN" $filename
#else
#echo "not generated by VASP"
#grep "total en" $filename
#fi
